- 1.1.19
- _NAME: MX KEYS S
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, scroll-ratchet-torque, smart-shift,
    thumb-scroll-invert, thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi, dpi_extended, speed-change, backlight-timed,
    led_control, led_zone_, rgb_control, rgb_zone_, brightness_control, per-key-lighting, reprogrammable-keys, persistent-remappable-keys, force-sensing,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, gesture2-gestures, gesture2-divert, gesture2-params, haptic-level, haptic-play, sidetone,
    equalizer, adc_power_management]
  _battery: 4100
  _modelId: B37800000000
  _sensitive: {backlight: true, backlight_duration_hands_in: true, backlight_duration_hands_out: true, backlight_duration_powered: true, backlight_level: true,
    change-host: true, disable-keyboard-keys: true, divert-keys: true, fn-swap: true, hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore,
    multiplatform: true}
  _serial: 215CD257
  _unitId: 215CD257
  _wpid: B378
  backlight: 1
  backlight_duration_hands_in: 30
  backlight_duration_hands_out: 30
  backlight_duration_powered: 30
  backlight_level: 0
  change-host: null
  disable-keyboard-keys: {1: false, 2: false, 4: false, 8: false, 16: false}
  divert-keys: {10: 0, 111: 1, 199: 0, 200: 0, 226: 0, 227: 0, 228: 0, 229: 0, 230: 0, 231: 0, 232: 0, 233: 0, 234: 0, 259: 1, 264: 1, 266: 1, 284: 1}
  fn-swap: false
  multiplatform: 0
- _NAME: MX Master 4
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi_extended, speed-change, backlight,
    backlight_level, backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control,
    rgb_zone_, brightness_control, per-key-lighting, fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys,
    m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B04200000000
  _sensitive: {change-host: true, divert-keys: true, dpi: true, force-sensing: true, haptic-level: true, hires-scroll-mode: true, hires-smooth-invert: true,
    hires-smooth-resolution: true, reprogrammable-keys: true, scroll-ratchet: true, scroll-ratchet-torque: true, smart-shift: true, thumb-scroll-invert: true,
    thumb-scroll-mode: true}
  _serial: F6763408
  _unitId: F6763408
  _wpid: B042
  change-host: null
  divert-keys: {82: 0, 83: 1, 86: 1, 195: 1, 196: 0, 416: 1}
  dpi: 1000
  force-sensing: {0: 6821}
  haptic-level: 60
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {82: 82, 83: 83, 86: 86, 195: 195, 196: 196, 416: 416}
  scroll-ratchet: 2
  scroll-ratchet-torque: 75
  smart-shift: 50
  thumb-scroll-invert: true
  thumb-scroll-mode: false
